import {UserLdap} from './userldap';

export const LDAP_USERS: UserLdap[] = [
  {
    login: 'test.v8',
    nom: 'V8',
    prenom: 'Test',
    motDePasse: null,
    classe: 'I2',
    groupe: null,
    mail: 'test.v8@epsi.fr',
    role: 'ROLE_USER',
    bts: false,
    btsParcours: '',
    btsNumero: '0',
    active: true,
    nomComplet: 'V8 Test'
  },
  {
    login: 'test.v5',
    nom: 'v5',
    prenom: 'Test',
    motDePasse: null,
    classe: 'I2',
    groupe: null,
    mail: 'test.v5@epsi.fr',
    role: 'ROLE_USER',
    bts: false,
    btsParcours: '',
    btsNumero: '0',
    active: false,
    nomComplet: 'v5 Test'
  },
  {
    login: 'test.v1',
    nom: 'V1',
    prenom: 'Test',
    motDePasse: null,
    classe: 'B1',
    groupe: null,
    mail: 'test.v1@epsi.fr',
    role: 'ROLE_USER',
    bts: true,
    btsParcours: 'SLAM',
    btsNumero: '0123456789',
    active: true,
    nomComplet: 'V1 Test'
  },
  {
    login: 'test.v2',
    nom: 'V2',
    prenom: 'Test',
    motDePasse: null,
    classe: 'B2',
    groupe: null,
    mail: 'test.v2@epsi.fr',
    role: 'ROLE_USER',
    bts: true,
    btsParcours: 'SLAM',
    btsNumero: '0',
    active: true,
    nomComplet: 'V2 Test'
  },
  {
    login: 'paul.duponD',
    nom: 'DUPOND',
    prenom: 'Paul',
    motDePasse: null,
    classe: 'B2',
    groupe: null,
    mail: 'paul.dupond@epsi.fr',
    role: 'ROLE_USER',
    bts: false,
    btsParcours: '',
    btsNumero: '',
    active: true,
    nomComplet: 'DUPOND Paul'
  },
  {
    login: 'jean.dupont',
    nom: 'DUPONT',
    prenom: 'Jean',
    motDePasse: null,
    classe: 'B2',
    groupe: null,
    mail: 'jean.dupont@epsi.fr',
    role: 'ROLE_USER',
    bts: true,
    btsParcours: 'SLAM',
    btsNumero: '0123456789',
    active: true,
    nomComplet: 'DUPONT Jean'
  },
  {
    login: 'test.v3',
    nom: 'V3',
    prenom: 'Test',
    motDePasse: null,
    classe: 'B3',
    groupe: null,
    mail: 'test.v3@epsi.fr',
    role: 'ROLE_USER',
    bts: false,
    btsParcours: '',
    btsNumero: '0',
    active: true,
    nomComplet: 'V3 Test'
  },
];

